### ISSUE TITLE
Part IV C: Average annual manpower

### ISSUE THREAD

**Issue by ec-mcs** [ESPD/ESPD-Translation#10]
Number of managerial staff: this is referred also in the following cell on average man power. One of the two is to be eliminated.

**Comment by ec-mcs** [comment]
**Current**
The economic operator's average annual manpower and the number of managerial staff for the last three years were as follows:
**Should be**
The economic operator's average annual manpower for the last three years were as follows:
**Location**
- Where: https://ec.europa.eu/growth/tools-databases/espd/request/eo/exclusion
- File: espd-en-20160705.XLSX
- Link: https://github.com/ESPD/ESPD-Translation/blob/master/espd-service-excel-files/espd-en-20160705.XLSX
Row: 320

**Comment by tsirafa** [comment]
issue encoded in JIRA
