### ISSUE TITLE
Part III A: Grounds relating to criminal convictions

### ISSUE THREAD

**Issue by ec-mcs** [ESPD/ESPD-Translation#15]
Part III A: Grounds relating to criminal convictions with relation to the duration of the period of exclusion it should be precised that it is to be reported “insofar as established directly in the conviction”

**Comment by ec-mcs** [comment]
**Current**
Length of the period of exclusion
**Should be**
Insofar as established directly in the conviction, length of the period of exclusion
**Location**
- Where: https://ec.europa.eu/growth/tools-databases/espd/request/eo/exclusion
- File: espd-en-20160705.XLSX
- Link: https://github.com/ESPD/ESPD-Translation/blob/master/espd-service-excel-files/espd-en-20160705.XLSX Row: 347

**Comment by tsirafa** [comment]
issue encoded in JIRA
