### ISSUE TITLE
Part I: Informazioni sulla pubblicazione

### ISSUE THREAD

**Issue by ec-mcs** [ESPD/ESPD-Translation#3]
Parte I: informazioni sulla procedura di appalto e sull’amministrazione aggiudicatrice o ente aggiudicatore
Se non è pubblicato un avviso di indizione di gara nella GUUE, l’amministrazione aggiudicatrice o e l’ente aggiudicatore deve compilare le informazioni in modo da permettere l’individuazione univoca della procedura di appalto

**Comment by ec-mcs** [comment]
**As this is an issue with the English version as well, it needs to be fixed there first**
**This is the adopted text**
If there is no call for competition in the OJEU, then the contracting authority or contracting entity must fill in the information allowing the procurement procedure to be unequivocally identified:
In case publication of a notice in the Official Journal of the European Union is not required, please give other information allowing the procurement procedure to be unequivocally identified (e. g. reference of a publication at national level)
**This is the current text in the ESPD service**
In case publication of a notice in the Official Journal of the European Union is not required, please give other information allowing the procurement procedure to be unequivocally identified (e. g. reference of a publication at national level)
**Proposal to combine the text**
If there is no call for competition in the Official Journal of the European Union or if it is not required to publish there, then the contracting authority or contracting entity must fill in information allowing the procurement procedure to be unequivocally identified (e. g. reference of a publication at national level)
**Location**
- Where: https://ec.europa.eu/growth/tools-databases/espd/request/ca/procedure
File: espd-en-20160705.XLSX
Link: https://github.com/ESPD/ESPD-Translation/blob/master/espd-service-excel-files/espd-en-20160705.XLSX
Row: 113

**Comment by tsirafa** [comment]
issue encoded in JIRA
