### ISSUE TITLE
Part III C: Bankruptcy, Insolvency, Arrangement...

### ISSUE THREAD

**Issue by ec-mcs** [ESPD/ESPD-Translation#5]
The sentence “Tali informazioni non devono essere indicate se l'esclusione degli operatori economici per tale caso riveste carattere obbligatorio ai sensi della normativa nazionale applicabile senza nessuna possibilità di deroga anche qualora l'operatore sia comunque in grado di eseguire il contratto” is misplaced since in the paper ESPD refers to the cases in which the EO will be able to perform the contract taking into account of national measures. L’indicazione di tali motivi, in questa modalità di visualizzazione del DGUE elettronico, non è invece prevista.

**Comment by ec-mcs** [comment]
**This applies as well for the English version**
The textual bug can be found in the following criteria:
- Bankruptcy
- Insolvency
- Arrangement with creditors
- Analogous situation like bankruptcy under national law
- Assets being administered by liquidator
- Business activities are suspended
**Currently**
The following text is part of the question from the buyer: "This information needs not be given if exclusion of economic operators in this case has been made mandatory under the applicable national law without any possibility of derogation where the economic operator is nevertheless able to perform the contract."
**Should be**
The text "This information" should come after the question to the company. It should be:
"Indicate reasons for being able nevertheless to perform the contract. **This information needs not be given if exclusion of economic operators in this case has been made mandatory under the applicable national law without any possibility of derogation where the economic operator is nevertheless able to perform the contract.**"
**Location**
- Where: https://ec.europa.eu/growth/tools-databases/espd/request/eo/exclusion
- File: espd-en-20160705.XLSX
- Link: https://github.com/ESPD/ESPD-Translation/blob/master/espd-service-excel-files/espd-en-20160705.XLSX
Row: 373 should be added,  217, 219, 221, 223, 225, 227 sentence should be removed

**Comment by tsirafa** [comment]
issue encoded in JIRA
