### ISSUE TITLE
Part IV B: Financial ratio

### ISSUE THREAD

**Issue by ec-mcs** [ESPD/ESPD-Translation#8]
Missing: “Ad esempio, rapporto tra attività e passività” (E.g. the ratio between assets and liabilities.)

**Comment by ec-mcs** [comment]
We will make the adjustment
**From**
Concerning the financial ratios specified in the relevant notice, the procurement documents or the ESPD, the economic operator declares that the actual values for the required ratios are as follows:
**To**
Concerning the financial ratios (like the ratio between assets and liabilities) specified in the relevant notice, the procurement documents or the ESPD, the economic operator declares that the actual values for the required ratios are as follows:
**Location**
- Where: https://ec.europa.eu/growth/tools-databases/espd/request/ca/procedure
- File: espd-en-20160705.XLSX
- Link: https://github.com/ESPD/ESPD-Translation/blob/master/espd-service-excel-files/espd-en-20160705.XLSX
- Row: 228

**Comment by tsirafa** [comment]
issue encoded in JIRA
